AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for Amsa Frontend and Backend

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

Resources:
  # Security Group for EC2
  AmsaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and Backend API
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  AmsaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0a716d3f3b16d290c  # Ubuntu 22.04
      SecurityGroupIds:
        - !Ref AmsaSecurityGroup
      Tags:
        - Key: Name
          Value: "Amsa-EC2-Instance"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          sudo apt update && sudo apt upgrade -y

          # Install dependencies
          sudo apt install -y git nginx curl unzip
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo npm install -g pm2 serve

          # Prepare frontend and backend directories
          sudo mkdir -p /var/www/frontend-amsa-ajinkya
          sudo mkdir -p /home/ubuntu/frontend-amsa-ajinkya
          sudo mkdir -p /home/ubuntu/backend-amsa-ajinkya
          sudo chown -R ubuntu:ubuntu /var/www/frontend-amsa-ajinkya /home/ubuntu

          # Configure Nginx for frontend + backend proxy
          cat <<EOF | sudo tee /etc/nginx/sites-available/amsa
          server {
              listen 80;
              server_name _;

              root /var/www/frontend-amsa-ajinkya;
              index index.html;

              location / {
                  try_files \$uri /index.html;
              }

              location /api {
                  proxy_pass http://localhost:3001;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOF

          sudo ln -sf /etc/nginx/sites-available/amsa /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t || true
          sudo systemctl restart nginx
          sudo systemctl enable nginx

Outputs:
  PublicIP:
    Description: Public IP of EC2
    Value: !GetAtt AmsaEC2Instance.PublicIp
  PublicDNS:
    Description: Public DNS of EC2
    Value: !GetAtt AmsaEC2Instance.PublicDnsName
