AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for Amsa Frontend and Backend

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

Resources:
  # Security Group for EC2
  AmsaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, Backend API
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  AmsaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName                    # Matches deploy.yml KeyName
      ImageId: ami-0a716d3f3b16d290c          # Ubuntu 22.04 LTS in eu-north-1
      SecurityGroupIds:
        - !Ref AmsaSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          sudo apt update && sudo apt upgrade -y

          # Install basic dependencies
          sudo apt install -y git curl nginx unzip

          # Install Node.js 18 and PM2
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pm2 serve

          # Create directories for frontend and backend
          sudo mkdir -p /var/www/frontend-amsa-ajinkya
          sudo mkdir -p /home/ubuntu/frontend-amsa-ajinkya
          sudo mkdir -p /home/ubuntu/backend-amsa-ajinkya
          sudo chown -R ubuntu:ubuntu /home/ubuntu

Outputs:
  PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt AmsaEC2Instance.PublicIp

  PublicDNS:
    Description: Public DNS of the EC2 instance
    Value: !GetAtt AmsaEC2Instance.PublicDnsName
